apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
- target:
    kind: Kustomization
    name: cert-manager
    namespace: flux-system
  patch: |-
    - op: add
      path: /spec/patches/-
      value:
        patch: |
          - op: add
            path: /spec/values/nodeSelector
            value: {node-group-name: privileged-ng}
        target:
          kind: HelmRelease
          name: cert-manager
          namespace: cert-manager
    - op: add
      path: /spec/patches/-
      value:
        patch: |
          - op: add
            path: /spec/values/tolerations/-
            value:
              key: "privileged"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule" 
        target:
          kind: HelmRelease
          name: cert-manager
          namespace: cert-manager
- target:
    kind: GitRepository
    name: flux-infra
    namespace: flux-system
  patch: |-
    - op: replace
      path: /spec/ref/tag
      value: v1.0.3
