apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
- target:
    kind: Kustomization
    name: cert-manager
    namespace: flux-system
  patch: |-
    - op: add
      path: /spec/patches/-
      value:
        patch: |
          - op: add
            path: /spec/values/nodeSelector
            value: 'node-group-name: "privileged-ng"'
        target:
          kind: HelmRelease
          name: cert-manager
          namespace: cert-manager
