apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- infrastructure.yaml
- imagepolicy.yaml
# - vm-scrape-jobs.yaml

images:
- name: docker.io/victoriametrics/victoria-metrics
  newTag: v1.74.0 # {"$imagepolicy": "flux-system:victoria-metrics-vmsingle-steve-dev-cluster:tag"}

# generatorOptions:
#   disableNameSuffixHash: false
# configMapGenerator:
# - name: image-patches
#   literals:
#   - v1.74.0 
# configurations:
# - kustomizeconfig.yaml

# patches:
# Example of how to patch the Kustomization with a patch that will be applied to the objects it creates, in this example a HelmRelease
# - target:
#     kind: Kustomization
#     name: cert-manager
#     namespace: flux-system
#   patch: |-
#     - op: add
#       path: /spec/patches/-
#       value:
#         patch: |
#           - op: add
#             path: /spec/values/nodeSelector
#             value: {node-group-name: privileged-ng}
#         target:
#           kind: HelmRelease
#           name: cert-manager
#           namespace: cert-manager
#     - op: add
#       path: /spec/patches/-
#       value:
#         patch: |
#           - op: add
#             path: /spec/values/tolerations/-
#             value:
#               key: "privileged"
#               operator: "Equal"
#               value: "true"
#               effect: "NoSchedule" 
#         target:
#           kind: HelmRelease
#           name: cert-manager
#           namespace: cert-manager
# - target:
#     kind: GitRepository
#     name: flux-infra
#     namespace: flux-system
#   patch: |-
#     - op: replace
#       path: /spec/ref/tag
#       value: v1.0.4
