apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 10m
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-infra
    namespace: flux-system
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: certificates.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: challenges.acme.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clusterissuers.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: issuers.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: orders.acme.cert-manager.io
