# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: amazon-cloudwatch-fluent-bit-steve-dev-cluster
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: amazon-cloudwatch-fluent-bit
#   policy:
#     semver:
#       range: '>=2.0.0 <3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: victoria-metrics-vmsingle-steve-dev-cluster
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: victoria-metrics-vmsingle
  policy:
    semver:
      range: '>=1.72.0 <2.0.0'
---
