apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-storage
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: ./storage
  prune: true
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-crds
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-storage
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: ./crds
  prune: true
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-crds
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: ./namespaces
  prune: true
  timeout: 2m
---
# Required - need to make sure that the Victoria Metrics Operator is deployed before Victoria Metrics CRDs
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: victoria-metrics-operator
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-namespaces
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: ./apps/victoria-metrics/operator
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vm-operator
      namespace: victoria-metrics-operator
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-certs
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: ./certs
  prune: true
  postBuild:
    substitute:
      AWS_ACCOUNT_ID: "841310725496"
      AWS_REGION: "eu-west-1"
      CLUSTER_CONTACT_EMAIL: "lenscloud-platform@users.noreply.github.com"
      CLUSTER_NAME: "lc-staging1"
      ROUTE53_HOSTED_ZONE_ID: "Z00406503FU8D8OYQ3FZF"
  timeout: 2m
---
