apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - gitrepositories.yaml
  - imageupdateautomation.yaml
  - infrastructure.yaml
  - imagepolicy.yaml
  # - ../../../infrastructure/dev/steve-dev-cluster

patches:
  - target:
      kind: GitRepository
      name: flux-infra
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/ref/tag
        value: v4.1.2
