apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - gitrepositories.yaml
  - imageupdateautomation.yaml
  - infrastructure.yaml
  - ../../../infrastructure/dev/steve-dev-cluster
