---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://git@github.com/stevejr/flux-infra.git
  secretRef:
    name: flux-infra-ssh-credentials
  ref:
    tag: v1.0.0
  ignore: |
    # exclude all
    /*
    # path to crds
    !/cert-manager/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: cert-manager-crds
    namespace: flux-system
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: certificates.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: challenges.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clusterissuers.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: issuers.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: orders.cert-manager.io
