apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-operator.yaml
  - metabase.yaml

patches:
- target:
      kind: GitRepository
      name: metabase
      namespace: flux-system
  patch: |-
    - op: replace
      path: /spec/ref/tag
      value: v5.1.0
- target:
      kind: GitRepository
      name: istio-operator
      namespace: flux-system
  patch: |-
    - op: replace
      path: /spec/ref/tag
      value: v5.2.1
